### ISSUE TITLE
addEntry doesn't work

### ISSUE THREAD

**Issue by jhnns** [peerigon/clockodo#52]
The function parameters are slightly off which makes the function unusable. `customerId` should be `customersId` and `serviceId` should be `servicesId`.

**Comment by tannerbaum** [comment]
@jhnns But shouldn't the mapping take care of it? 
https://github.com/peerigon/clockodo/blob/4213e272dbee4190fd432073ac658fb5540f3ac3/src/internals/utilities/mapKeys.ts#L24

The parameter is written differently because it's only one ID so the 's' doesn't really make sense. If you want to argue that it should be the exact same when possible I wouldn't necessarily disagree.

**Comment by jhnns** [comment]
> But shouldn't the mapping take care of it?

`mapKeys` is only executed on query parameters, so no :)
